language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
        packages:
            - g++-6
            - clang-3.9

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-6

    - compiler: clang
      env: COMPILER=clang++-3.9

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y valgrind
  - pip install --user cpp-coveralls

before_script:
  - if [ "$COMPILER" = "g++-6"        ]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [ "$COMPILER" = "clang++-3.9"  ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi

script:
  - cmake CMakeLists.txt
  - make
  - ctest -T memcheck --output-on-failure

after_success:
  - if [ "$COMPILER" = "g++-6"        ]; then coveralls --include src --gcov-options '\-lp'; fi

notifications:
  email: false